<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Headless.NUnit" Version="11.3.10" />
        <PackageReference Include="coverlet.collector" Version="6.0.4" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="NUnit" Version="4.4.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.11.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\COMPASS.Tests.Common\COMPASS.Tests.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="App.axaml.cs">
        <DependentUpon>App.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

</Project>
