<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
    <PackageReference Include="HotAvalonia" Version="3.0.0" PrivateAssets="All" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\COMPASS.Common\COMPASS.Common.csproj" />
    <ProjectReference Include="..\COMPASS.Infra\COMPASS.Infra.csproj" />
  </ItemGroup>
</Project>
