<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>COMPASS</AssemblyName>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="HotAvalonia" Version="3.1.0" PrivateAssets="All" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\COMPASS.Common\COMPASS.Common.csproj" />
    <ProjectReference Include="..\COMPASS.Infra\COMPASS.Infra.csproj" />
  </ItemGroup>
</Project>
