<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.6" />
    <PackageReference Include="HotAvalonia" Version="3.0.0" PrivateAssets="All"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\COMPASS.Common\COMPASS.Common.csproj" />
    <ProjectReference Include="..\COMPASS.Infra\COMPASS.Infra.csproj" />
  </ItemGroup>
</Project>
