<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>COMPASS</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Label="Avalonia">
    <AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
    <AvaloniaXamlReportImportance>Normal</AvaloniaXamlReportImportance>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.0.4" PrivateAssets="All" />
    <PackageReference Include="HotAvalonia" Version="3.1.0" PrivateAssets="All" Publish="True" />
  </ItemGroup>

  <PropertyGroup>
    <HotAvaloniaMode>Balanced</HotAvaloniaMode>
    <HotAvaloniaHotkey>F11</HotAvaloniaHotkey>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\COMPASS.Common\COMPASS.Common.csproj" />
  </ItemGroup>
</Project>
