<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>2.0.0</Version>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Label="Avalonia">
    <AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
    <AvaloniaXamlReportImportance>Normal</AvaloniaXamlReportImportance>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
    <PackageReference Include="HotAvalonia" Version="3.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\COMPASS.Common\COMPASS.Common.csproj" />
  </ItemGroup>
</Project>
