<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <SelfContained>false</SelfContained>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Headless.NUnit" Version="12.0.3" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
        <PackageReference Include="NUnit" Version="4.6.1" />
        <PackageReference Include="NUnit.Analyzers" Version="4.13.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Source\COMPASS.Windows\COMPASS.Windows.csproj" />
      <ProjectReference Include="..\COMPASS.Tests.Common\COMPASS.Tests.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="App.axaml.cs">
        <DependentUpon>App.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

</Project>
