<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <!-- Some user have crash when opening trying to pick a file with the windows file explorer
         Setting CET compatibility to false is suggested in https://github.com/dotnet/wpf/issues/10305-->
    <CETCompat>false</CETCompat>
    <RootNamespace>COMPASS</RootNamespace>
    <AssemblyName>COMPASS</AssemblyName>
    <ApplicationIcon>COMPASS.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <StartupObject>COMPASS.App</StartupObject>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Media\CompassLogo.png" />
  </ItemGroup>

  <ItemGroup>

    <Content Include="COMPASS.ico" />

    <Resource Include="Media\CompassLogo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>

    <Content Include="Media\CoverPlaceholder.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <None Include="..\.editorconfig" Link=".editorconfig" />

    <Resource Include="Media\LoadingAnimation.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>

    <SplashScreen Include="Media\CompassFull.png" />

  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.0.0" />
    <PackageReference Include="Autoupdater.NET.Official" Version="1.9.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
    <PackageReference Include="FuzzySharp" Version="2.0.2" />
    <PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="itext" Version="9.4.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.4.0" />
    <PackageReference Include="log4net" Version="3.2.0" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.11.1" />
    <PackageReference Include="Magick.NET.SystemDrawing" Version="8.0.12" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.11.0.20250507" />
    <PackageReference Include="PDFtoImage" Version="5.2.0" />
    <PackageReference Include="Selenium.Support" Version="4.38.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.38.0" />
    <PackageReference Include="SharpCompress" Version="0.41.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.10" />
    <PackageReference Include="VirtualizingWrapPanel" Version="2.1.1" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.14" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>