name: Create Installer

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (*.*.*), no prefix'
        required: true
        type: string
      branch:
        description: 'the branch to checkout'
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        ref: ${{ inputs.branch }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -p:PublishProfile=FolderProfile.pubxml
      
      #upload the main exe so it can be signed
    - name: Upload app exe
      id: upload-exe
      uses: actions/upload-artifact@v4
      with:
        name: COMPASS_exe
        path: .\src\bin\Publish\win-x64\COMPASS.exe

    - name: Sign app
      id: signing-app
      uses: signpath/github-action-submit-signing-request@v0.4
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: 2f2c8b60-b250-4dd2-8827-045fa9cc65e6
        project-slug: COMPASS
        signing-policy-slug: test-signing
        github-artifact-id: ${{steps.upload-exe.outputs.artifact-id}}
        wait-for-completion: true
        output-artifact-directory: .\
      
    #singed app will be downloaded as a zip file, extract it and replace it unsiged exe with the singed one
    - name: Unzip and replace
      shell: pwsh
      run: Expand-Archive -Force .\COMPASS_exe.zip .\src\bin\Publish\win-x64\COMPASS.exe

    - name: Package
      run: iscc Deployment/install.iss

    - name: Upload installer
      id: upload-installer
      uses: actions/upload-artifact@v4
      with:
        name: COMPASS_Installer
        path: .\Deployment\Versions\${{ inputs.version }}\COMPASS_Setup_${{ inputs.version }}.exe

  sign-installer:
    name: sign intaller
    runs-on: windows-latest

    steps:
    - name: Code Signing
      id: signing
      uses: signpath/github-action-submit-signing-request@v0.4
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: 2f2c8b60-b250-4dd2-8827-045fa9cc65e6
        project-slug: COMPASS
        signing-policy-slug: test-signing
        github-artifact-id: ${{steps.upload-installer.outputs.artifact-id}}
        wait-for-completion: false


    

    